### ISSUE TITLE
登录注册页面

### ISSUE THREAD

**Issue by HTwo2O** [DuoRouLongShu/FilmReviewWeb-TeamWork-#2]

**Comment by QiuBin666** [comment]
5.22

issue签入：

实现验证码的功能

发现项目的BUG并报告：

暂无

与对应负责人的探讨交流：

验证码实现类的接口

今后准备实施的任务：

结合数据库测试登录注册功能

**Comment by QiuBin666** [comment]
5.22

issue签入：

实现验证码的功能

发现项目的BUG并报告：

暂无

与对应负责人的探讨交流：

验证码实现类的接口

今后准备实施的任务：

结合数据库测试登录注册功能

**Comment by smart6666** [comment]
5.24
-修改发送到前端的数据格式
-解决小bug

**Comment by QiuBin666** [comment]
5.24

- issue签入：

  前后端数据交互

- 发现项目的BUG并报告：

  数据提交有BUG，页面跳转BUG

- 与对应负责人的探讨交流：

  共同发现问题所在，进行多次修改和测试

- 今后准备实施的任务：

  对用户名敏感词进行校验，解决验证码刷新问题

**Comment by QiuBin666** [comment]
5.25

- 问题签入：

  用户名敏感词校验，验证码刷新问题

- 发现项目的BUG并报告：

  暂无

- 与对应负责人的探讨交流：

  个人任务，个人测试

- 未来准备实施的任务：

  功能测试与完善，页面美化
