### ISSUE TITLE
影库页面

### ISSUE THREAD

**Issue by HTwo2O** [DuoRouLongShu/FilmReviewWeb-TeamWork-#4]
搜索框、电影陈列

**Comment by DuoRouLongShu** [comment]
5.22
初步完成了电影首页面的前端页面布局，以及规定了接口文档交给后台，等待后台开发完成

**Comment by DuoRouLongShu** [comment]
5.22

issue签入：网站首页的前端部分

- 发现项目的BUG并报告

  暂无

- 与对应负责人的探讨交流

  首页的接口文档基本完成，请求负责首页后端的迅速抽空查看并检查开发

- 今后准备实施的任务

  完成数据的传送渲染

**Comment by HTwo2O** [comment]
5.22

issue签入：影库页面的后台

* 发现项目的BUG并报告

  暂无

* 与对应负责人的探讨交流

  完成了搜索框接口

* 今后准备实施的任务

  看前端需求提供新的接口

**Comment by QiuBin666** [comment]
5.23
问题签入：登录注册的前端
-发现项目的BUG并报告
 前后端数据交互失败
-与负责人的探讨交流
 根据BUG的提示信息逐个排除
-提前准备实施的任务
 页面的美化和功能的完善

**Comment by Mazin-hub** [comment]
5.24

- 发现项目的BUG并报告

  暂无

- 与对应负责人的探讨交流

  完成搜索框的初步调试和对接。

- 今后准备实施的任务

  调整页面布局。
