### ISSUE TITLE
特定电影页面

### ISSUE THREAD

**Issue by HTwo2O** [DuoRouLongShu/FilmReviewWeb-TeamWork-#5]
包括资料、影评展示、打分功能、写影评功能

**Comment by HTwo2O** [comment]
5.22

- 发现项目的BUG并报告

  暂无

- 与对应负责人的探讨交流

   电影页面后台接口今天基本完成，待前端运用测试

- 今后准备实施的任务
开始做其他页面

**Comment by Mazin-hub** [comment]
5.22

- 发现项目的BUG并报告

  暂无

- 与对应负责人的探讨交流

  电影页面与后台接口的对接，实现相应逻辑代码编写。

- 今后准备实施的任务

  完成特定电影页面的测试，减少bug。

**Comment by Mazin-hub** [comment]
5.23

- 发现项目的bug并报告

  无

- 与对应负责人的探讨交流

  电影具体页面与后台接口的对接更新，测试运行

- 今后准备实施的任务

  完成用户中心的js代码，准备跟后台对接。

**Comment by Mazin-hub** [comment]
5.24

- 发现项目的bug并报告

  无

- 与对应负责人的探讨交流

  电影具体页面的接口最终测试

- 今后准备实施的任务

  和后台对接、完成用户个人中心的测试运行
