### ISSUE TITLE
管理员中心

### ISSUE THREAD

**Issue by HTwo2O** [DuoRouLongShu/FilmReviewWeb-TeamWork-#6]
用户数据库、审核影评、设置首页、电影数据库、查看反馈

**Comment by HTwo2O** [comment]
5.24
后台

* 发现项目的BUG并报告
   暂无

* 与对应负责人的探讨交流
   讨论接口细节

* 今后准备实施的任务
   继续完成剩余接口

**Comment by DuoRouLongShu** [comment]
5.24

管理员页面的前端布局部分

- 发现项目的BUG并报告

  暂无

- 与对应负责人的探讨交流

  布局基本完成，接口还没接入

- 今后准备实施的任务

完成数据渲染

**Comment by HTwo2O** [comment]
5.25
后台

* 发现项目的BUG并报告
  暂无

* 与对应负责人的探讨交流
  今天完成了添加、修改、删除电影三接口

* 今后准备实施的任务
  完成测试工作

**Comment by HTwo2O** [comment]
5.26
后台

*  发现项目的BUG并报告
  暂无

*  与对应负责人的探讨交流
  完成所有接口

*  今后准备实施的任务
  完成测试工作，改进代码
