### ISSUE TITLE
用户个人中心

### ISSUE THREAD

**Issue by HTwo2O** [DuoRouLongShu/FilmReviewWeb-TeamWork-#7]
用户历史影评、反馈、修改个人信息

**Comment by Mazin-hub** [comment]
5.24

- 发现项目的bug并报告

  无

- 与对应负责人的探讨交流

  更改接口文档

- 今后准备实施的任务

  和后台对接、完成用户个人中心的测试运行

**Comment by Mazin-hub** [comment]
5.25

- 发现项目的bug并报告

  无

- 与对应负责人的探讨交流

  对接接口文档数据

- 今后准备实施的任务

  和后台对接、继续完成用户个人中心的测试运行

**Comment by Mazin-hub** [comment]
5.26

- 发现项目的bug并报告

   无

- 与对应负责人的探讨交流

  根据接口文档数据、完成测试

- 今后准备实施的任务

  拓展个人中心的功能

**Comment by smart6666** [comment]
5.27

- 与前端人员交流接口问题

- 实现查询和保存用户信息接口

**Comment by Mazin-hub** [comment]
5.27

- 发现项目的bug并报告

  图片上传

- 与对应负责人的探讨交流

  修改接口

- 今后准备实施的任务

  合并前端的资源，找bug
